package entity;
// Generated 3/06/2018 04:40:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idexamen;
     private String nombreexamen;
     private Set tipolecturaexamens = new HashSet(0);
     private Set tipoescrituraexamens = new HashSet(0);

    public Examen() {
    }

	
    public Examen(String nombreexamen) {
        this.nombreexamen = nombreexamen;
    }
    
    public Examen(String nombreexamen,Set tipolecturaexamens) {
        this.nombreexamen = nombreexamen;
        this.tipolecturaexamens = tipolecturaexamens;
    }
    
//    public Examen(String nombreexamen,Set tipoescrituraexamens) {
//        this.nombreexamen = nombreexamen;
//        this.tipoescrituraexamens = tipoescrituraexamens;
//    }
    
    public Examen(String nombreexamen, Set tipolecturaexamens, Set tipoescrituraexamens) {
       this.nombreexamen = nombreexamen;
       this.tipolecturaexamens = tipolecturaexamens;
       this.tipoescrituraexamens = tipoescrituraexamens;
    }
   
    public Integer getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(Integer idexamen) {
        this.idexamen = idexamen;
    }
    public String getNombreexamen() {
        return this.nombreexamen;
    }
    
    public void setNombreexamen(String nombreexamen) {
        this.nombreexamen = nombreexamen;
    }
    public Set getTipolecturaexamens() {
        return this.tipolecturaexamens;
    }
    
    public void setTipolecturaexamens(Set tipolecturaexamens) {
        this.tipolecturaexamens = tipolecturaexamens;
    }
    public Set getTipoescrituraexamens() {
        return this.tipoescrituraexamens;
    }
    
    public void setTipoescrituraexamens(Set tipoescrituraexamens) {
        this.tipoescrituraexamens = tipoescrituraexamens;
    }




}


