package entity;
// Generated 3/06/2018 04:40:11 PM by Hibernate Tools 4.3.1



/**
 * Respuestapreguntas generated by hbm2java
 */
public class Respuestapreguntas  implements java.io.Serializable {


     private Integer idRespuestasPreguntas;
     private Preguntalectura preguntalectura;
     private String textoRespuesta;
     private boolean respuestaRespuesta;

    public Respuestapreguntas() {
    }

    public Respuestapreguntas(Preguntalectura preguntalectura, String textoRespuesta, boolean respuestaRespuesta) {
       this.preguntalectura = preguntalectura;
       this.textoRespuesta = textoRespuesta;
       this.respuestaRespuesta = respuestaRespuesta;
    }
   
    public Integer getIdRespuestasPreguntas() {
        return this.idRespuestasPreguntas;
    }
    
    public void setIdRespuestasPreguntas(Integer idRespuestasPreguntas) {
        this.idRespuestasPreguntas = idRespuestasPreguntas;
    }
    public Preguntalectura getPreguntalectura() {
        return this.preguntalectura;
    }
    
    public void setPreguntalectura(Preguntalectura preguntalectura) {
        this.preguntalectura = preguntalectura;
    }
    public String getTextoRespuesta() {
        return this.textoRespuesta;
    }
    
    public void setTextoRespuesta(String textoRespuesta) {
        this.textoRespuesta = textoRespuesta;
    }
    public boolean isRespuestaRespuesta() {
        return this.respuestaRespuesta;
    }
    
    public void setRespuestaRespuesta(boolean respuestaRespuesta) {
        this.respuestaRespuesta = respuestaRespuesta;
    }




}


