package entity;
// Generated 3/06/2018 04:40:11 PM by Hibernate Tools 4.3.1



/**
 * Tipoescrituraexamen generated by hbm2java
 */
public class Tipoescrituraexamen  implements java.io.Serializable {


     private Integer idtipoescritura;
     private Examen examen;
     private String textotipoescritura;
     private String imagentipoescritura;

    public Tipoescrituraexamen() {
    }

    public Tipoescrituraexamen(Examen examen, String textotipoescritura, String imagentipoescritura) {
       this.examen = examen;
       this.textotipoescritura = textotipoescritura;
       this.imagentipoescritura = imagentipoescritura;
    }
   
    public Integer getIdtipoescritura() {
        return this.idtipoescritura;
    }
    
    public void setIdtipoescritura(Integer idtipoescritura) {
        this.idtipoescritura = idtipoescritura;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getTextotipoescritura() {
        return this.textotipoescritura;
    }
    
    public void setTextotipoescritura(String textotipoescritura) {
        this.textotipoescritura = textotipoescritura;
    }
    public String getImagentipoescritura() {
        return this.imagentipoescritura;
    }
    
    public void setImagentipoescritura(String imagentipoescritura) {
        this.imagentipoescritura = imagentipoescritura;
    }




}


