package entity;
// Generated 3/06/2018 04:40:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipolecturaexamen generated by hbm2java
 */
public class Tipolecturaexamen  implements java.io.Serializable {


     private Integer idtipolectura;
     private Examen examen;
     private String textotipolectura;
     private String imagentipolectura;
     private Set preguntalecturas = new HashSet(0);

    public Tipolecturaexamen() {
    }

	
    public Tipolecturaexamen(Examen examen, String textotipolectura, String imagentipolectura) {
        this.examen = examen;
        this.textotipolectura = textotipolectura;
        this.imagentipolectura = imagentipolectura;
    }
    public Tipolecturaexamen(Examen examen, String textotipolectura, String imagentipolectura, Set preguntalecturas) {
       this.examen = examen;
       this.textotipolectura = textotipolectura;
       this.imagentipolectura = imagentipolectura;
       this.preguntalecturas = preguntalecturas;
    }
   
    public Integer getIdtipolectura() {
        return this.idtipolectura;
    }
    
    public void setIdtipolectura(Integer idtipolectura) {
        this.idtipolectura = idtipolectura;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getTextotipolectura() {
        return this.textotipolectura;
    }
    
    public void setTextotipolectura(String textotipolectura) {
        this.textotipolectura = textotipolectura;
    }
    public String getImagentipolectura() {
        return this.imagentipolectura;
    }
    
    public void setImagentipolectura(String imagentipolectura) {
        this.imagentipolectura = imagentipolectura;
    }
    public Set getPreguntalecturas() {
        return this.preguntalecturas;
    }
    
    public void setPreguntalecturas(Set preguntalecturas) {
        this.preguntalecturas = preguntalecturas;
    }




}


