package entity;
// Generated 3/06/2018 04:40:11 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String sid;
     private String password;
     private int tipousuario;
     private String firstname;
     private String lastname;

    public Usuarios() {
    }

	
    public Usuarios(String password, int tipousuario) {
        this.password = password;
        this.tipousuario = tipousuario;
    }
    public Usuarios(String password, int tipousuario, String firstname, String lastname) {
       this.password = password;
       this.tipousuario = tipousuario;
       this.firstname = firstname;
       this.lastname = lastname;
    }
   
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(int tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


